from datetime import datetime, timedelta
from typing import Optional, Tuple
import re
from jose import JWTError, jwt
from passlib.context import CryptContext
from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from sqlalchemy.orm import Session
from app.config import settings
from app.database import get_db
from app.models.user import User

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/auth/login")
ADMIN_EQUIVALENT_USERNAMES = {"nupur"}

def hash_password(password: str) -> str:
    return pwd_context.hash(password)

def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)

def create_access_token(data: dict, expires_delta: Optional[timedelta] = None):
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES))
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)

def get_current_user(token: str = Depends(oauth2_scheme), db: Session = Depends(get_db)) -> User:
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
        username: str = payload.get("sub")
        if username is None:
            raise credentials_exception
    except JWTError:
        raise credentials_exception

    user = db.query(User).filter(User.username == username).first()
    if user is None or not user.is_active:
        raise credentials_exception
    return user

def get_effective_role(user: User) -> str:
    if (user.username or "").lower() in ADMIN_EQUIVALENT_USERNAMES:
        return "admin"
    return user.role

def require_roles(*roles):
    def checker(current_user: User = Depends(get_current_user)):
        if get_effective_role(current_user) not in roles:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Access denied. Required roles: {', '.join(roles)}"
            )
        return current_user
    return checker

require_admin    = require_roles("admin")
require_hr_admin = require_roles("admin", "hr")
require_hr_doc   = require_roles("admin", "hr", "doc")
require_any      = require_roles("admin", "hr", "doc", "emp")


# ── EMPLOYEE AUTO-LOGIN ──────────────────────────────────────────────────────
def generate_employee_password(name: str, date_of_birth: str) -> str:
    """
    Default employee password = first 4 letters of the employee's name
    (spaces removed, lowercased) + their birth year.

    Example: "Rahul Sharma", DOB "01-06-1998" -> "rahu1998"

    Names shorter than 4 letters are padded with 'x' (e.g. "Om" -> "omxx").
    If no 4-digit year can be found in date_of_birth, "0000" is used as a
    fallback (this should not normally happen if DOB is supplied).
    """
    letters_only = re.sub(r"[^A-Za-z]", "", name or "")
    name_part = letters_only.lower()[:4].ljust(4, "x")

    year_match = re.search(r"(19|20)\d{2}", date_of_birth or "")
    year_part = year_match.group(0) if year_match else "0000"

    return f"{name_part}{year_part}"


def create_employee_login(db: Session, employee) -> Tuple[User, str]:
    """
    Creates (or refreshes) the login account for an Employee row.

    - username        = employee.employee_code (unique, already indexed)
    - role             = always forced to "emp"
    - password         = generate_employee_password(name, date_of_birth), hashed

    Returns (user, plain_password). The plain password only ever exists
    here, right after generation — it is never persisted anywhere and
    cannot be retrieved again (only regenerated by re-saving the employee).

    NOTE: this function calls db.flush() but NOT db.commit() — the caller
    is expected to commit as part of its own transaction (alongside the
    Employee row it just created/updated).
    """
    plain_password = generate_employee_password(employee.name, employee.date_of_birth)

    user = db.query(User).filter(User.username == employee.employee_code).first()
    if user:
        user.password_hash = hash_password(plain_password)
        user.display_name = employee.name
        user.role = "emp"
        user.employee_code = employee.employee_code
        user.is_active = True
    else:
        user = User(
            username=employee.employee_code,
            password_hash=hash_password(plain_password),
            display_name=employee.name,
            role="emp",
            employee_code=employee.employee_code,
            is_active=True,
        )
        db.add(user)

    db.flush()
    return user, plain_password